"""Hand-maintained skill relationships, grounded in README and SKILL.md prose."""

RELATIONSHIPS = {
    "scope": {"uses": ["epic", "ui-craft", "plan-review", "prototype", "research"], "requirements": ""},
    "review": {"uses": ["code-review", "persona-review", "plan-review"], "requirements": ""},
    "epic": {"uses": ["research", "scope", "ui-craft", "ticket"], "requirements": "GitHub CLI; composes with `research`, `scope`'s interview mode, `ui-craft`"},
    "implement": {"uses": ["tdd", "code-review"], "requirements": "`tdd` and `code-review` from this pack"},
    "openspec-adopt": {"uses": [], "requirements": "GitHub CLI; global `@fission-ai/openspec@1.11.0`"},
    "orchestrate": {"uses": ["ticket", "ui-craft", "code-review", "plan-review", "persona-review", "research"], "requirements": "Codex CLI for GPT-tier sub-agents; table re-benchmarked per its bundled procedure"},
    "ticket": {"uses": ["scope", "plan-review", "review", "spin-worktree", "orchestrate", "reviewer-memory"], "requirements": "GitHub CLI for the bundled issues binding, one binding page per other tracker; composes with `scope`, `plan-review`, `review`, `spin-worktree`, `orchestrate`; `reviewer-memory` from this pack"},
    "ui-craft": {"uses": ["drive-local-webapp", "spin-worktree"], "requirements": "`drive-local-webapp` for rendered review; `spin-worktree` for live base comparison; parallel-agent support is recommended"},
    "cbm-onboard": {"uses": [], "requirements": "`codebase-memory-mcp` on `PATH`; v0.10.8+ for ephemeral lifecycle"},
    "ci-design": {"uses": [], "requirements": ""},
    "clean": {"uses": ["codebase-design", "domain-modeling"], "requirements": "`codebase-design` from this pack; `domain-modeling` optional"},
    "code-review": {"uses": ["orchestrate", "reviewer-memory"], "requirements": "`orchestrate` is an optional integration used for reviewer routing when installed; `reviewer-memory` from this pack; parallel-agent support recommended; GitHub CLI to fetch an originating issue; see [docs/review-round-mining.md](docs/review-round-mining.md) for the mined evidence behind the fix protocol and the round cap"},
    "codebase-design": {"uses": ["domain-modeling"], "requirements": ""},
    "codebase-memory": {"uses": [], "requirements": "`codebase-memory-mcp` for graph queries; activation fails open without it"},
    "domain-modeling": {"uses": ["codebase-design"], "requirements": ""},
    "drive-local-webapp": {"uses": [], "requirements": "Node.js 20+; installs Playwright locally"},
    "handoff": {"uses": [], "requirements": ""},
    "persona-review": {"uses": ["orchestrate"], "requirements": "Private data repo for persona memory; GitHub CLI for mining real-colleague profiles; parallel-agent support recommended"},
    "plan-review": {"uses": ["orchestrate", "persona-review", "reviewer-memory"], "requirements": "`orchestrate` is an optional integration used for reviewer routing when installed; `reviewer-memory` from this pack; parallel-agent support recommended; `persona-review` optional for load-bearing plans; the round-count evidence behind its rules is in [docs/review-round-mining.md](docs/review-round-mining.md)"},
    "pr-body": {"uses": [], "requirements": "A PreToolUse hook that hard-denies `gh pr create` until the body is scored, installed separately from `hooks/`"},
    "preflight": {"uses": ["plan-review"], "requirements": ""},
    "prototype": {"uses": [], "requirements": ""},
    "research": {"uses": [], "requirements": ""},
    "reviewer-memory": {"uses": [], "requirements": ""},
    "say-less": {"uses": [], "requirements": "Optional prompt hook for always-on digest; see [docs/overlay.md](docs/overlay.md) and the [measured comparison](docs/before-after.md)"},
    "spin-worktree": {"uses": [], "requirements": "Git; GitHub CLI only for `--pr` discovery"},
    "tdd": {"uses": [], "requirements": ""},
    "writing-for-agents": {"uses": [], "requirements": "Hand-only; invoke by name"},
}
